### ISSUE TITLE
Upgrade google-cloud-storage to version  1.113.8

### ISSUE THREAD

**Issue by JiriOndrusek** [quarkiverse/quarkus-google-cloud-services#113]
I'm working on camel-quarkus extension for google-storage https://github.com/apache/camel-quarkus/issues/2421

This extension uses `google-cloud-storage` library of version `1.113.4`
````
<groupId>com.google.cloud</groupId>
<artifactId>google-cloud-storage</artifactId>
````
Camel component uses slightly higher version - `1.113.8`

It would be nice to upgrade version of this extension to  `1.113.8` and make this extension aligned with camel.

**Comment by loicmathieu** [comment]
We manage google cloud extension via the library BOM, this is the advised way of managing dependency from the Google Cloud Library Team.

So I would prefere to upgrade the version of the library BOM instead of updated a single library.

I don't know if Camel manage each version of each Google Cloud services idenpendently but if it's the case they should move to the BOM if possible.

**Comment by JiriOndrusek** [comment]
@loicmathieu 

I see, that camel is also using bom:

```
<dependency>
                <groupId>com.google.cloud</groupId>
                <artifactId>libraries-bom</artifactId>
                <version>${google-cloud-bom-version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

where version of bom  is `16.3.0` (see https://github.com/apache/camel/blob/main/parent/pom.xml#L218)

**Comment by loicmathieu** [comment]
Master is `16.1.0` I can increase it on the next release but I'm prototyping using the Google Cloud BOM inside the Quarkus BOM to align all versions from it. I'll update this issue with feedback.

**Comment by loicmathieu** [comment]
Main now uses the latest BOM and as dependabot is installed updates will be made as soon as available.
I'm closing this one as we use the most recent version.
