### ISSUE TITLE
Extension for setup GCP logging

### ISSUE THREAD

**Issue by Thibaud-R** [quarkiverse/quarkus-google-cloud-services#146]
Would it be possible to configure Quarkus Logging for GCP logging ?
As quarkus ignore java.util.logging.config.file, it is not possible to configure it with the GCP LoggingHandler like explianed in https://cloud.google.com/logging/docs/setup/java#the_javautillogging_handler
The only workaround I found, is to register and configure the handler manually ...
The console handler produces logs but the level of the log message is not set in the severity of the LogEntry, etc ...

But maybe I missed something ...
Otherwise, a new extension would be nice, as it was suggested in https://stackoverflow.com/questions/67870277/is-there-is-a-way-to-set-up-google-cloud-logging-for-quarkus#comment119986717_67870277 :)

**Comment by loicmathieu** [comment]
There is a JUL log Handler, `com.google.cloud.logging.LoggingHandler` so it should be easy to create an extension to use this handler with Quarkus.

**Comment by Thibaud-R** [comment]
For information the quarkus-logging-json from quarkiverse, resolve my problem (last version):
* it avoid both writing the log in stdout / stderr and sending well formatted logs to gcp loggging api (=> only to stdout)
* the json produces in stdout is well parsed by GCP logging and the JUL log level, is set as the severity (difference with the quarkus-logging-json extension from quarkus)

The problem remains if you need to send logs to a remote GCP logging console and use the GCP log Handler.
