### ISSUE TITLE
Consider making `quarkus.google.cloud.project-id` optional

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-google-cloud-services#150]
Camel provides some alternative ways to configure GCP, e.g. in camel-pubsub, users can pass their projectId through the route definition - see https://camel.apache.org/components/3.11.x/google-pubsub-component.html#_uri_format
This works quite well, but users have to always provide `quarkus.google.cloud.project-id` even if it is actually not needed. Thus we'd appreciate if `quarkus.google.cloud.project-id` could please be made optional.

This is very similar to amqphub/quarkus-qpid-jms#11 and https://github.com/quarkusio/quarkus/issues/18231

**Comment by loicmathieu** [comment]
@ppalaga currently, if not set, it'll default to `ServiceOptions.getDefaultProjectId();` via build step so it's not really mandatory.

I can make it optional, but currently only pubsub and bigtable didn't madatne it, all other extensions would fail.

What you can do, however, is to produce a `RunTimeConfigurationDefaultBuildItem` with the projectId from the route. But as I understand it, you can have multiple route from multiple project which is not supported currently by the extensions.

**Comment by ppalaga** [comment]
> currently, if not set, it'll default to `ServiceOptions.getDefaultProjectId();` via build step so it's not really mandatory.

The main motivation behind this request is to be able to create and configure the clients programmatically either from the user application code or from our extension code. In case I do not provide `quarkus.google.cloud.project-id`, would `ServiceOptions.getDefaultProjectId()` return normally without throwing any exception?

> I can make it optional, but currently only pubsub and bigtable didn't madatne it, all other extensions would fail.

Sorry, I am not sure I follow this. What do you mean with "didn't madatne it"? 

> What you can do, however, is to produce a `RunTimeConfigurationDefaultBuildItem` with the projectId from the route. But as I understand it, you can have multiple route from multiple project which is not supported currently by the extensions.

Yes, as I mentioned above, we normally create our own clients as needed. If a client configured your way is available via CDI, then we may use it under some circumstances. But we'd like our users not to be forced to configure clients your way.

I am afraid, `RunTimeConfigurationDefaultBuildItem` would nor really help because first, we are currently not able to parse the route definitions at build time and even if we were, end users may use placeholders that pull values like projectId from the environment so we even can't tell what the value is at build time.

**Comment by ppalaga** [comment]
> > currently, if not set, it'll default to `ServiceOptions.getDefaultProjectId();` via build step so it's not really mandatory.
> 
> The main motivation behind this request is to be able to create and configure the clients programmatically either from the user application code or from our extension code. In case I do not provide `quarkus.google.cloud.project-id`, would `ServiceOptions.getDefaultProjectId()` return normally without throwing any exception?

Now I see your comment in #159. Let me test it.

**Comment by loicmathieu** [comment]
> Sorry, I am not sure I follow this. What do you mean with "didn't madatne it"?

_mandate_ ;) I mean that most extensions needs the property to initialize a CDI bean, but not pubsub nor bigtable
