### ISSUE TITLE
new feature BigQuery Storage API

### ISSUE THREAD

**Issue by neXus1987** [quarkiverse/quarkus-google-cloud-services#194]
Google BigQuery released a new Storage API (also more cost efficient including free contigents):

https://cloud.google.com/bigquery/docs/write-api

**Comment by zanmagerl** [comment]
I can start on this (as I have a use case for this) if you do not object @loicmathieu ?

**Comment by loicmathieu** [comment]
@zanmagerl OK, go! :+1:

**Comment by neXus1987** [comment]
great news, thanks a lot!!!
