### ISSUE TITLE
Enhance FirestoreProducer With Option to Setup Emulator

### ISSUE THREAD

**Issue by SvenWoltmann** [quarkiverse/quarkus-google-cloud-services#208]
### Problem

To use the Firestore emulator, you need to set the `FIRESTORE_EMULATOR_HOST` environment variable. That is not always feasible. For example, it's impossible to set an environment variable dynamically for integration tests. 

That would, for example, be necessary to use the [Testcontainers](https://www.testcontainers.org/modules/gcloud/) library, which starts the emulator on a random port.

Therefore, it would be beneficial to be able also to set the emulator host via an application property.

### Proposed Solution

I propose to add an application property `firestore.emulator.host` and evaluate it in `FirestoreProducer` as follows:

```
@ApplicationScoped
public class FirestoreProducer {

    @Inject
    GoogleCredentials googleCredentials;

    @Inject
    GcpConfigHolder gcpConfigHolder;

    @ConfigProperty(name = "firestore.emulator.host")  // added line
    Optional<String> emulatorHost;                     // added line

    @Produces
    @Singleton
    @Default
    public Firestore firestore() {
        GcpBootstrapConfiguration gcpConfiguration = gcpConfigHolder.getBootstrapConfig();
        return FirestoreOptions.newBuilder().setCredentials(googleCredentials)
                .setHost(emulatorHost.orElse(null))                                                          // added line
                .setCredentials(emulatorHost.isPresent() ? NoCredentials.getInstance() : googleCredentials)  // added line
                .setProjectId(gcpConfiguration.projectId.orElse(null))
                .build()
                .getService();
    }
}
```

Additional benefits: 
* As the `NoCredentials` credentials are used, you don't need to create the mocked `GoogleCredentials` producer anymore.
* This would work even if you do not use the `firestore.emulator.host` application property but the `FIRESTORE_EMULATOR_HOST` environment variable, which would also be mapped to the config property.

(By the way: I also removed the unnecessary `throws IOException` from the `firestore()` method.)

### Usage With Testcontainers

A Testcontainer can then be configured as follows:

```
public class FirestoreTestResource implements QuarkusTestResourceLifecycleManager {

  private FirestoreEmulatorContainer emulator;

  @Override
  public Map<String, String> start() {
    emulator =
        new FirestoreEmulatorContainer(
            DockerImageName.parse("gcr.io/google.com/cloudsdktool/cloud-sdk:316.0.0-emulators"));

    emulator.start();

    return Map.of("firestore.emulator.host", emulator.getEmulatorEndpoint());
  }

  @Override
  public void stop() {
    emulator.stop();
  }
}
```

... and used in an integration test as follows:

```
@QuarkusTest
@QuarkusTestResource(FirestoreTestResource.class)
class IntegrationTest {

    @Inject
    Firestore firestore;

    ...
}
```

If you agree that this is a useful extension, I'll be happy to create a PR.

**Comment by loicmathieu** [comment]
Emulators are already supported on some extensions so adding support to more of them is a good thing ;)

On Cloud Storage, we define the setting as `host-override`, see https://github.com/quarkiverse/quarkus-google-cloud-services/blob/main/storage/runtime/src/main/java/io/quarkiverse/googlecloudservices/storage/runtime/StorageConfiguration.java
