### ISSUE TITLE
UserError: Classes that should be initialized at run time got initialized during image building - `Slf4jLoggerFactory`

### ISSUE THREAD

**Issue by mpeddada1** [quarkiverse/quarkus-google-cloud-services#294]
Hi all,

**Description of the issue**
We recently introduced a change in libraries-bom 25.4.0 to [explicitly initialize `Slf4JLoggerFactory` and `Log4JLogger`  at run-time](https://github.com/googleapis/gax-java/blob/0f0996c7c4bea2af3a01979fd3e21cfb6a96d565/gax-grpc/src/main/resources/META-INF/native-image/com.google.api/gax-grpc/native-image.properties#L6) which seems to be resulting in the following error with Quarkus:

```
Step #1: Error: Classes that should be initialized at run time got initialized during image building:
Step #1:  io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory the class was requested to be initialized at run time (from jar:file:///workspace/native-image-samples/native-image-samples-quarkus/quarkus-integration-test/target/quarkus-integration-test-0.14.2-SNAPSHOT-native-image-source-jar/lib/com.google.api.gax-grpc-2.18.1.jar!/META-INF/native-image/com.google.api/gax-grpc/native-image.properties with 'io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory'). To see why io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory got initialized use --trace-class-initialization=io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory
Step #1: 
Step #1: com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
Step #1:  io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory the class was requested to be initialized at run time (from jar:file:///workspace/native-image-samples/native-image-samples-quarkus/quarkus-integration-test/target/quarkus-integration-test-0.14.2-SNAPSHOT-native-image-source-jar/lib/com.google.api.gax-grpc-2.18.1.jar!/META-INF/native-image/com.google.api/gax-grpc/native-image.properties with 'io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory'). To see why io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory got initialized use --trace-class-initialization=io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory
Step #1: 
Step #1: 	at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
Step #1: 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:555)
Step #1: 	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:168)
Step #1: 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:727)
Step #1: 	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
Step #1: 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:727)
Step #1: 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
Step #1: 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
Step #1: 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:410)
Step #1: 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:594)
Step #1: 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:124)
Step #1: 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:624)
Step #1: [quarkus-integration-test-0.14.2-SNAPSHOT-runner:1884]      [total]:  32,073.30 ms,  3.37 GB
Step #1: # Printing build artifacts to: /workspace/native-image-samples/native-image-samples-quarkus/quarkus-integration-test/target/quarkus-integration-test-0.14.2-SNAPSHOT-native-image-source-jar/quarkus-integration-test-0.14.2-SNAPSHOT-runner.build_artifacts.txt
Step #1: Error: Image build request failed with exit status 1
Step #1: To see how the classes got initialized, use --trace-class-initialization=io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory
```

The reason for the change was to avoid running into this warning: `Warning: class initialization of class io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory failed with exception java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory to explicitly request delayed initialization of this class.
` when running native image compilation with services like Pub/Sub. 

**Environment**
JDK:
```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)
```
libraries-bom version: 25.4.0

Reproducer: https://github.com/mpeddada1/simple-quarkus-test

We were wondering if you had experienced this before? We would love to get your insights on how you handle logging your end and any potential solution that could help achieve compatibility? Thank you so much.

cc @meltsufin , @suztomo

**Comment by aigens** [comment]
seeing the same error with bom 25.4.0

**Comment by loicmathieu** [comment]
@mpeddada1 @aigens Quarkus GCP extensions include the Google library BOM and the Google native support library so to be sure that you don't have any issue you must not include them yourself.

Seeing dependabot PR https://github.com/quarkiverse/quarkus-google-cloud-services/pull/293 build, there is an issue with the new version of the Google library BOM, I'll have a look when I had time which should not be soon as I'll be on PTO soon.

**Comment by mpeddada1** [comment]
Thanks for your response @loicmathieu! A quick note on the issue, the `libraries-bom` 25.4.0 comes with the configurations so please also consider testing PR https://github.com/quarkiverse/quarkus-google-cloud-services/pull/293 without the native-image-support dependency.

**Comment by loicmathieu** [comment]
@mpeddada1 I don't understand, we need the native-image-support dependency or native build will not work. Does the libraries-bom include the dependency management for it now ?

**Comment by meltsufin** [comment]
@loicmathieu The native image support is now included in the libraries themselves and doesn't require a separate dependency.

**Comment by loicmathieu** [comment]
Great ! I'll remove it and see if it fixes the issue.
We normally use netty from Quarkus and not the embedded one from gRPC. The issue may be caused by a needed exclusion of netty embedded somewhere.

**Comment by loicmathieu** [comment]
@meltsufin I remove the native image support library and fixes the Netty native image issue. You can check https://github.com/quarkiverse/quarkus-google-cloud-services/pull/296, on Quarkus we have builtin support to defere class initialization at runtime and this is what was needed to make BigQuery (in fact Apache Arrow) works on native. We also have a quarkus-netty extension that makes netty works in native so I remove the dependency to nettyt-shaded and add ours.

In the case of native image issue, this is an iterative process, you need to trace the offending class initlalization (via --trace-class-initialization=org.apache.arrow.memory.DefaultAllocationManagerFactory for eg, that can be pass to the Quarkus build thanks to -DQuarkus.native.additional-build-args), then initialize at runtime the offender, then build, then trace, then initialize, ... Untill you found all the classes that causes the issue. You can saw on the PR that there is 4 classes that needs to be runtime initialized.

Idealy, these runtime initialized class needs to be declared upstream on the bigquery library, I can open a PR for it if you want, then i'll be able to remove them from here.

**Comment by meltsufin** [comment]
@loicmathieu thanks for investigating the issue and upgrading to the latest libraries-bom. @mpeddada1 recently looked at Apache Arrow configs for GraalVM in BigQuery. So, I'll let her comment on that when she has a chance. I think you can merge #296 for now, and we can update that with the next libraries-bom release when Arrow configs move to BigQuery, where we ultimately want that them to live.

**Comment by mpeddada1** [comment]
Thanks for the thorough investigation and upgrade @loicmathieu! I added a comment to #296. As @meltsufin mentioned, ideally we would like the configurations to live in Bigquery but curious to learn more about where they are needed. Would you be able to share a stacktrace?
