### ISSUE TITLE
Unable to resolve Secret Manager value when using yaml configuration

### ISSUE THREAD

**Issue by marceloverdijk** [quarkiverse/quarkus-google-cloud-services#314]
Having an `application.properties` file with:

```
%prod.my.username=${sm//MY_USERNAME}
```

works on GCP.

I'm now trying to do the same in an `application.yaml` file, but the value is not resolved unfortunately

```
"%prod":
  my:
    username: ${sm//MY_USERNAME}
```

it gives:

```
java.util.NoSuchElementException: SRCFG00011: Could not expand value sm//MY_USERNAME in property my.username
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:453)
	at io.quarkus.runtime.generated.Config.<clinit>(Unknown Source)
```

I also tried escaping like `username: \${sm//MY_USERNAME}` but then the value resolves to simply `"${sm//MY_USERNAME}"` and not the actual value from the Secret Manager.

Do I need to use another format?

**Comment by danielcamargoeti** [comment]
> Having an `application.properties` file with:
> 
> ```
> %prod.my.username=${sm//MY_USERNAME}
> ```
> 
> works on GCP.
> 
> I'm now trying to do the same in an `application.yaml` file, but the value is not resolved unfortunately
> 
> ```
> "%prod":
>   my:
>     username: ${sm//MY_USERNAME}
> ```
> 
> it gives:
> 
> ```
> java.util.NoSuchElementException: SRCFG00011: Could not expand value sm//MY_USERNAME in property my.username
> 	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:453)
> 	at io.quarkus.runtime.generated.Config.<clinit>(Unknown Source)
> ```
> 
> I also tried escaping like `username: \${sm//MY_USERNAME}` but then the value resolves to simply `"${sm//MY_USERNAME}"` and not the actual value from the Secret Manager.
> 
> Do I need to use another format?

Same issue on my end

**Comment by danielcamargoeti** [comment]
I've found a workaround by defining an empty default value. Something like this:

```yaml
"%prod":
  my:
    username: ${sm//MY_USERNAME:""}
```

**Comment by loicmathieu** [comment]
@danielcamargoeti did you try to quote the value to be sure YAML interpret it as a Sring ?

```yml
"%prod":
  my:
    username: "${sm//MY_USERNAME}"
```

**Comment by loicmathieu** [comment]
@danielcamargoeti have you try the suggestion I made a few weeks ago .

**Comment by loicmathieu** [comment]
Closing it as not heard from the issuer from some time.
