### ISSUE TITLE
Feature Request: Support for Firebase Authentication

### ISSUE THREAD

**Issue by bernardocoferre** [quarkiverse/quarkus-google-cloud-services#335]
- Add Firebase Authentication support

**Comment by bernardocoferre** [comment]
@loicmathieu Do you know if there's any particular reason why Firebase Auth is not supported yet by this extension? If it's ok, I'll be happy to contribute and work on it.

**Comment by loicmathieu** [comment]
@bernardocoferre no reason, if you want to implement it I would be happy to help you with the implementation and review it.

**Comment by bernardocoferre** [comment]
@loicmathieu thank you! I've opened [this](https://github.com/quarkiverse/quarkus-google-cloud-services/pull/336) draft PR. It does not have any integration tests yet, and the reason for that is because I think Google does not provide any public Docker images with the emulator. Also, the only way to point to the emulator would be setting an environment variable, which would require a little more trick.

With that said, I was thinking of adding a new module for this specific test, similar to what was done with `google-cloud-function` and `app-engine`.  What are your thoughts about it?

**Comment by loicmathieu** [comment]
@bernardocoferre I didn't know how firebase is working but I need an integration test at least that I can run manually to check that everything works correctly (the README must include the steps to deploy the IT and test it).

**Comment by bernardocoferre** [comment]
Understood. I'll provide an integration test to be manually ran, then. Thank you!

**Comment by bernardocoferre** [comment]
@loicmathieu Do you know when will the new version be released? Just asking so I can close this issue.

**Comment by loicmathieu** [comment]
As #336 fixes it I'll close the issue.
I plan to release it soon, maybe for Quarkus 2.15, as this extension is in the platform I prefere to sync releases with Quarkus release but the new version can be used with older one.
To be aware of the new version you can watch this repo for new version.
