### ISSUE TITLE
Resolve GCP project ID from the metadata server

### ISSUE THREAD

**Issue by kostacasa** [quarkiverse/quarkus-google-cloud-services#4]
Many GCP products and services are augmented with a [metadata server](https://cloud.google.com/compute/docs/storing-retrieving-metadata). This endpoint provides useful information about the instance and the environment. 

One of the resources it exposes is the ability to retrieve the project ID under which the service is running. Specifically, it can be retrieved using:
`http://metadata.google.internal/computeMetadata/v1/project/project-id`

Instead of configuring it explicitly via application.properties, the services could resolve this dynamically when the metadata server is available.

Caveat: Even though metadata servers are running directly on the compute instances, since a HTTP request is still necessary to retrieve the values, this could have a small impact to cold start times in constrained environments like Cloud Run/Functions.

**Comment by loicmathieu** [comment]
The request to the metadata server never goes out of the application host so it should not have a huge impact on start times.
The best is to add this feature behind an `enabled` property, disabled by default, so it's  a developer choice to use it.

**Comment by loicmathieu** [comment]
We can then decide to enable it by default from the Google Cloud Functions extension when this extension is here for example.

**Comment by loicmathieu** [comment]
PR #89 resolves the project ID from `ServiceOptions.getDefaultProjectId()` which will use the metadata server if available.
So I'm closing it.
