### ISSUE TITLE
Release 2.0.0 missing in github releases

### ISSUE THREAD

**Issue by paloliska** [quarkiverse/quarkus-google-cloud-services#424]
Release 2.0.0 missing in github releases. As I could see in maven central this version is already released.

**Comment by loicmathieu** [comment]
Hi,
Thanks for the hint.
I usually release in GitHub soon after the release is published to the Quarkus platform but as the Quarkus 3 release took a bit longer I deploy the release and kind of forget it ;)

I just released it.
