### ISSUE TITLE
Support Opentelemetry trace propagator for pubsub

### ISSUE THREAD

**Issue by vigneshsn** [quarkiverse/quarkus-google-cloud-services#451]
We have use case to pass the opentelemetry trace and span id's across the pubsub. it would be great, if we have this implemented as part quarkus extension rather than writing our own implementation. BTW we are using Quarkus extension for opentelemetry.

**Comment by jfbenckhuijsen** [comment]
@loicmathieu have also been looking at this for a bit last week, might be able to pick this up. Not sure on timeline, but seems doable.

**Comment by jfbenckhuijsen** [comment]
Upstream tracking issue for support in the Pubsub library itself: https://issuetracker.google.com/issues/183608476?pli=1

**Comment by jfbenckhuijsen** [comment]
Semantic conventions for Pubsub spec: https://opentelemetry.io/docs/specs/semconv/messaging/gcp-pubsub/

**Comment by jfbenckhuijsen** [comment]
Feature request in google-apis/java-pubsub https://github.com/googleapis/java-pubsub/issues/1981

**Comment by vigneshsn** [comment]
@jfbenckhuijsen  thanks for your effort in pushing google pubsub to support OTEL.
