### ISSUE TITLE
Add option to write to stdout in Google Cloud Logging

### ISSUE THREAD

**Issue by zanmagerl** [quarkiverse/quarkus-google-cloud-services#453]
Hey,
Google Cloud Logging offers great support for writing JSON logs with traces and stracktraces to GCP via Google Cloud Operations API. But there is a problem if you run the application in the GCP environment as you have duplicated logs: ones from stdout and ones from API. It would be great to add support that we flush structured JSONs to stdout and let Google take care of the ingestion. Something similar is supported in the official Java Google Cloud Logging [library](https://github.com/googleapis/java-logging#alternative-way-to-ingest-logs-in-google-cloud-managed-environments).

I would be happy to implement this myself, but I want to check if this would be merged before I start on implementation.

**Comment by loicmathieu** [comment]
Hi @zanmagerl 
If it's just a configuration option, I would be happy to accept such PR.
