### ISSUE TITLE
PubSub DevServices not working against release version

### ISSUE THREAD

**Issue by nahguam** [quarkiverse/quarkus-google-cloud-services#459]
The emulator container dev service is not starting for me with released versions of the pubsub extension.
However, if I checkout the main branch and install it to my local maven repository and use that version (`1.3.0-SNAPSHOT`) then it works as expected.

Following the guide here: https://quarkiverse.io/quarkiverse-docs/quarkus-google-cloud-services/main/pubsub.html#_using_the_dev_service

### To Replicate

```
mvn io.quarkus:quarkus-maven-plugin:3.2.0.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=pubsub-quickstart \
    -Dextensions="resteasy-reactive-jackson,quarkus-google-cloud-pubsub"
cd pubsub-quickstart

echo "quarkus.google.cloud.pubsub.devservice.enabled=true" >> src/main/resources/application.properties

mvn quarkus:dev
```

### Expected Result:

The emulator container starts.

### Actual Result:

The emulator container does not start and the following entry is in the log:

```
 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.google.cloud.pubsub.devservice.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

**Comment by zZHorizonZz** [comment]
I think that's because there wasn't a release. It will be included in version 2.2.0, but I don't know when it is planned.

**Comment by nahguam** [comment]
> I think that's because there wasn't a release. It will be included in version 2.2.0, but I don't know when it is planned.

No, but if I also pin to the latest release `2.1.0`, which is what the bom resolves to - it's the same result.

**Comment by nahguam** [comment]
It's probably unrelated but I noticed a typo in the package name: https://github.com/quarkiverse/quarkus-google-cloud-services/blob/a19a0d2e6808315731db8d35e9cede8fe3798e94/pubsub/deployment/src/main/java/io/quarkiverse/googlecloudservices/pubsub/deployement/PubSubDevServiceProcessor.java#L1

`deploy-e-ment`

**Comment by zZHorizonZz** [comment]
> No, but if I also pin to the latest release 2.1.0, which is what the bom resolves to - it's the same result.

What I meant was that the latest release of this extension is 2.1.0, and the pubsub dev service was added after the 2.1.0 was released. So, we are now waiting until the 2.2.0 version of this extension is released.

> It's probably unrelated but I noticed a typo in the package name:

If you want, you can open a PR with a fix, or I can do it.

**Comment by nahguam** [comment]
> > No, but if I also pin to the latest release 2.1.0, which is what the bom resolves to - it's the same result.
> 
> What I meant was that the latest release of this extension is 2.1.0, and the pubsub dev service was added after the 2.1.0 was released. So, we are now waiting until the 2.2.0 version of this extension is released.
> 
> > It's probably unrelated but I noticed a typo in the package name:
> 
> If you want, you can open a PR with a fix, or I can do it.

Ah, I see what you mean! I did not notice that!

I can open a quick PR for the type.

**Comment by loicmathieu** [comment]
Hi,
Yes,  I didn't do a new release as there is an issue with Apache Arrow in native which is used by BigQuery so I wait for a fix upstream to make a new release based on Quarkus 3.2.
