### ISSUE TITLE
Firestore: using listDocuments() requires EmulatorCredentials when running with dev services

### ISSUE THREAD

**Issue by jfbenckhuijsen** [quarkiverse/quarkus-google-cloud-services#554]
Operations like Firestore.listDocuments() require specific Admin credentials. In the production environment this is ensured by the default GCP credentials, however, when connecting to an emulator (i.e. via Dev Services) specific credentials need to be provided, for which the EmulatorCredentials class can be used.

The current integration logic does not provide this functionality, therefore these operations cannot be used in an emulator environment.

**Comment by jfbenckhuijsen** [comment]
Example implementation based on the reference docs. Running this example results in an error when dev services are enabled.

`
package org.acme;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

import com.google.api.core.ApiFuture;
import com.google.api.core.ApiFutures;
import com.google.cloud.firestore.CollectionReference;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.Query;
import com.google.cloud.firestore.QuerySnapshot;
import com.google.cloud.firestore.WriteResult;

@Path("/firestore")
public class FirestoreResource {
    @Inject
    Firestore firestore; // Inject Firestore

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String firestore() throws ExecutionException, InterruptedException {
        // Insert 3 persons
        CollectionReference persons = firestore.collection("persons");
        List<ApiFuture<WriteResult>> futures = new ArrayList<>();
        futures.add(persons.document("1").set(new Person(1L, "John", "Doe")));
        futures.add(persons.document("2").set(new Person(2L, "Jane", "Doe")));
        futures.add(persons.document("3").set(new Person(3L, "Charles", "Baudelaire")));
        ApiFutures.allAsList(futures).get();

        return StreamSupport.stream(persons.listDocuments().spliterator(), false)
                .map(r -> {
                    try {
                       return  r.get().get();
                    } catch (InterruptedException | ExecutionException e) {
                        throw new RuntimeException(e);
                    }
                }).map(document -> document.getId() + " - " + document.getString("firstname") + " "
                        + document.getString("lastname") + "\n")
                .collect(Collectors.joining());
//
        // Search for lastname=Doe
//        Query query = persons.whereEqualTo("lastname", "Doe");
//        ApiFuture<QuerySnapshot> querySnapshot = query.get();
//        return querySnapshot.get().getDocuments().stream()
//                .map(document -> document.getId() + " - " + document.getString("firstname") + " "
//                        + document.getString("lastname") + "\n")
//                .collect(Collectors.joining());
    }
}
`

**Comment by jfbenckhuijsen** [comment]
Branch with implemented testcase: https://github.com/jfbenckhuijsen/quarkus-google-cloud-services/tree/firestore-admin-queries

**Comment by jfbenckhuijsen** [comment]
Anyone able to respond to this?

**Comment by loicmathieu** [comment]
Hi,

I think we can switch to `Credentials` everywhere, this has the advantage of making it easy to mock the credentials and stick to the lower level type in the hierarchy that is used almost everywhere.

As you said, this is not the case for FirebaseAdmin, people that uses FirebaseAdmin must provide an object of type GoogleCredentials.

This PR did exactly that: https://github.com/quarkiverse/quarkus-google-cloud-services/pull/579

As you said, we should be able, when using emulator, to automatically create such overridden bean, if you're willing to do this (ideally for all supported service that provides emulator configuration) a PR would be highly welcome.

**Comment by jfbenckhuijsen** [comment]
On it!

**Comment by jfbenckhuijsen** [comment]
#602 created

**Comment by jfbenckhuijsen** [comment]
As far as I could tell, only Firestore has specific EmulatorCredentials to use. Spanner has a setEmulatorHost, but that has already been implemented. So AFAIK this should complete this issue

**Comment by jfbenckhuijsen** [comment]
@loicmathieu tested a local SNAPSHOT version of the code vs my own setup, seems to work nicely, so looks like we can close this issue?

**Comment by loicmathieu** [comment]
Yes, thanks for reporting!

Fixed by #602
