### ISSUE TITLE
Stackdriver Monitoring Support

### ISSUE THREAD

**Issue by murphye** [quarkiverse/quarkus-google-cloud-services#56]
Please see this for comparison:
https://cloud.spring.io/spring-cloud-gcp/reference/html/#stackdriver-monitoring

Also would depend on this issue for native support:
https://github.com/quarkusio/quarkus/issues/13349

**Comment by ebullient** [comment]
The stackdriver extension for micrometer is moving to quarkiverse also, here: 
https://github.com/quarkiverse/quarkiverse-micrometer-registry/pull/3

Once both are in quarkiverse, the quarkiverse micrometer stackdriver extension will pull the two bits together.

**Comment by loicmathieu** [comment]
Stackdriver metrics are available since a long time in https://github.com/quarkiverse/quarkus-micrometer-registry

Closing this issue.
