### ISSUE TITLE
SecurityIdentity identity is not an instanceof JsonWebToken

### ISSUE THREAD

**Issue by NickPaul41** [quarkiverse/quarkus-google-cloud-services#592]
The example code for getting a `JsonWebToken` does not seem to work.
[firebase-admin](https://docs.quarkiverse.io/quarkus-google-cloud-services/main/firebase-admin.html)

```
@Path("/app")
public class FirebaseAppResource {

    @Inject
    FirebaseApp firebaseApp;

    @Inject
    SecurityIdentity identity;

    @GET
    @Path("/options")
    @Produces(MediaType.APPLICATION_JSON)
    public FirebaseOptions getOptions() {
        if(identity instanceof JsonWebToken) {
            System.out.println("JWT: " + ((JsonWebToken) identity).getClaim("email"));
        }

        return firebaseApp.getOptions();
    }

}
```

When debugging my project identity is not an instanceof `JsonWebToken`.

I'm able to do a workaround by casting `identity.getPrincipal()` to a `FirebasePrincipal`.

```
@GET
    @Produces(MediaType.APPLICATION_JSON)
    public FirebaseOptions getOptions() {
        FirebasePrincipal fbp;
        if(identity.getPrincipal() instanceof FirebasePrincipal) {
            fbp = (FirebasePrincipal) identity.getPrincipal();
            System.out.println("FirebasePrincipal: " + fbp.getClaim("email"));
        }

        return firebaseApp.getOptions();
    }

```

Is this an issue with the documentation or should identity be an instance of `JsonWebToken`?

**Comment by jfbenckhuijsen** [comment]
FirebasePrincipal is a JsonWebToken, so seems like the docs are not correct. 

```
if(identity.getPrincipal() instanceof JsonWebToken) {
      System.out.println("JWT: " + ((JsonWebToken) identity.getPrincipal()).getClaim("email"));
}
```

I think this should be the correct code in the example, right @loicmathieu 

PR to fix this --> https://github.com/quarkiverse/quarkus-google-cloud-services/pull/657
