### ISSUE TITLE
Google Cloud Services - PubSub(quarkus-google-cloud-pubsub) does not expose QuarkusPubSub class

### ISSUE THREAD

**Issue by Hemantkumar-Chigadani** [quarkiverse/quarkus-google-cloud-services#595]
I was trying to following example given here for pub-sub
https://docs.quarkiverse.io/quarkus-google-cloud-services/main/pubsub.html

But unfortunately `QuarkusPubSub` class no where to find

`quarkus-google-cloud-pubsub` is published correctly?

**Comment by loicmathieu** [comment]
It is not yet released.
I'll create a new release today if I found the time as it's a long time since I didn't make one.

**Comment by loicmathieu** [comment]
The new version is published, it's the 2.8.0 which will be integrated in the next platform release (should be 3.8.3).

**Comment by SimonScholz** [comment]
Actually I am using 3.8.3, but the `QuarkusPubSub`  class is still not available :(

**Comment by loicmathieu** [comment]
Yes sorry I release too late for 3.8.3. It will be in 3.9 and 3.8.4.
