### ISSUE TITLE
Quarkus support for Whatsapp Notifications

### ISSUE THREAD

**Issue by ashtonhogan** [quarkiverse/quarkus-google-cloud-services#616]
Is this available yet?

**Comment by loicmathieu** [comment]
Hi,
This repository is for the Google Cloud extensions of Quarkus.
You should redirect you question to the Quarkus repository itself, see https://quarkus.io/support/

**Comment by ashtonhogan** [comment]
@loicmathieu Perhaps firebase can send Whatsapp notifications?

**Comment by loicmathieu** [comment]
@ashtonhogan no idea, Firebase extension was provided by an external contributor.
