### ISSUE TITLE
Firebase Auth Doc Inaccuracy

### ISSUE THREAD

**Issue by cinnes** [quarkiverse/quarkus-google-cloud-services#640]
A couple of inaccuracies in the `firebase-admin` docs:
https://github.com/quarkiverse/quarkus-google-cloud-services/blob/312109a8fe5bf15692a56a75102f95f7fe5ce91d/docs/modules/ROOT/pages/firebase-admin.adoc?plain=1#L76-L80

- L76 `quarkus.google.cloud.firebase-admin.auth.enable` should be `quarkus.google.cloud.firebase.auth.enabled`
- L80 `quarkus.google.cloud.firebase-admin.auth.enabled` should be `quarkus.google.cloud.firebase.auth.enabled`

Correct config path is visible here:
https://github.com/quarkiverse/quarkus-google-cloud-services/blob/312109a8fe5bf15692a56a75102f95f7fe5ce91d/firebase-admin/deployment/src/main/java/io/quarkiverse/googlecloudservices/firebase/admin/deployment/authentication/FirebaseAuthConfiguration.java#L7

**Comment by jfbenckhuijsen** [comment]
@loicmathieu  656
