### ISSUE TITLE
Register Severity enum for reflection to support native applications that use gcp logging

### ISSUE THREAD

**Issue by wabrit** [quarkiverse/quarkus-google-cloud-services#678]
I'm using version 2.11.0 of the quarkus-google-cloud-logging quarkiverse extension so that I can log to GCP.

Logging works as expected for non-native Quarkus applications, but in native all logs appear with DEFAULT severity in GCP console rather than INFO, DBUG etc.

This is because the `LoggingHandler#transform` method uses Gson to serialize a value of the `com.google.cloud.logging.Severity` enum, and in native builds this always serializes to `null` unless that class is registered for reflection.

Rather than rely on applications to do this, the quarkus google cloud logging extension should ensure that the enum is registered with `ReflectiveClassBuildItem` in the processor (presumably as a `@BuildStep` annotated method of the `LoggingBuildSteps` class).

**Comment by loicmathieu** [comment]
Thanks for the issue, this is easy to fix, as you have it sorted out maybe you want to propose a PR? 
Otherwise I'll take care of it.

**Comment by wabrit** [comment]
Hi @loicmathieu - I'm happy to have a go at this one, given that it looks like just a few additional lines.

**Comment by loicmathieu** [comment]
Great! Thank you!
