### ISSUE TITLE
Emulator auth when using both PubSub and FirebaseAdmin

### ISSUE THREAD

**Issue by jfbenckhuijsen** [quarkiverse/quarkus-google-cloud-services#690]
Hey @loicmathieu, 

I think I've run into an issue when using both pubsub and the FirebaseAdmin module when using the emulator. 

As per https://cloud.google.com/pubsub/docs/emulator#pubsub-emulator-java for PubSub we need to use the "NoCredentials" class when connecting to the emulator

As per https://stackoverflow.com/questions/63781560/connecting-to-firestore-emulator-from-java-admin-sdk you need to use the EmulatorCredentials when connecting to the emulator.

As per https://docs.quarkiverse.io/quarkus-google-cloud-services/main/#emulators we can configure both Credentials as a CDI bean and a CredentialsProvider as CDI bean.

You can configure the "Credentials" to be the EmulatorCredentials and the CredentialsProvider to be the NoCredentialsProvider, and then it seems to work, but this is hardly intuitive for a user of the library (and is not documented).

I'd propose we add config options like we did for the Firestore situation to have the library automatically configure the right credentials for the emulator to use and avoid the hassle of needing to create that mock bean.

We can easily achieve this by using Instance<Credentials> to retrieve it at runtime if the emulator is switched off I'd say?

Lemme know what you think, can create the PR of course.

**Comment by loicmathieu** [comment]
Well, this is annoying I agree, and the blame is upsteam ;) 

But yes, if you can provide something that ease these cases, I'll be happy to review it

**Comment by jfbenckhuijsen** [comment]
Initial version !705

**Comment by jfbenckhuijsen** [comment]
Need to look into the Firebase Admin version still btw

**Comment by jfbenckhuijsen** [comment]
This should be fixed with merging of #707 and #705
