### ISSUE TITLE
Artifact quarkus-google-cloud-secret-manager is missing in MVN Repo

### ISSUE THREAD

**Issue by edorosh** [quarkiverse/quarkus-google-cloud-services#85]
Hi all! I tried to use Secret Manager package in my Quarkus (1.11.2) project and have a problem with downloading it.

I added these lines to my pom.xml file
```yaml
<dependency>
    <groupId>io.quarkiverse.googlecloudservices</groupId>
    <artifactId>quarkus-google-cloud-secret-manager</artifactId>
    <version>0.4.0</version>
</dependency>
```

And mvn fails to download it. I checked the results at https://mvnrepository.com/artifact/io.quarkiverse.googlecloudservices. There is no artifact quarkus-google-cloud-secret-manager as well. Can you please check if the artifact is published?

**Comment by loicmathieu** [comment]
Hi @edorosh secret  manager will be available on 0.5, it has been merged yesterday only.
The documentation is on master so it may shows some stuff that are not yet available.

I'll plan to make a release soon, certainly after Quarkus 1.12 to avoid creating multiple release.

**Comment by loicmathieu** [comment]
If you really want to test it, you must clone this repo and install it locally, we didn't publish snapshot releases yet?

**Comment by edorosh** [comment]
Thanks @loicmathieu for the comments! It's clear

**Comment by loicmathieu** [comment]
FYI I release 0.5.0 today that includes Google Cloud Secret Manager

**Comment by edorosh** [comment]
Awesome! Thanks
