### ISSUE TITLE
Provide endpoint-override properties

### ISSUE THREAD

**Issue by PeterUlb** [quarkiverse/quarkus-google-cloud-services#91]
> Contributions are always welcome, but better create an issue to discuss them prior to any contributions.

I've just found this repository and realized I'd rather use this than creating my producers in every single project again and again.
The feature I miss most currently is to provide a custom endpoint.

`StorageOptions.newBuilder().setCredentials(credentials).setHost(gcpConfiguration.hostOverride.orElse(null)).build().getService();`

The sqs lib has the property `quarkus.sqs.endpoint-override` for that.

Use case: In my tests I start testcontainers which usually expose a locahost:port location. Then I use a custom credential (extends GoogleCredentials implements ServiceAccountSigner) to communicate with the mock server.

On a related note, is there a reason why `GcpCredentialProducer` produces `GoogleCredentials` instead of the more generic `Credentials`? Not a big problem, just requires a non-null returning implementation of `refreshAccessToken` when talking with the mock server, while Credentials can be extended with returning all null values.

**Comment by loicmathieu** [comment]
Hi, thanks for open this issue ;)

For the ability to override the default host of storage, yes, it's a good addition ;)
If you plan to work on it, can you also add an integration test for Storage ? I'll be possible after this addition (you can take for exemple what I did for BigTable: https://github.com/quarkiverse/quarkus-google-cloud-services/blob/master/integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/BigtableResourceTest.java).

> On a related note, is there a reason why GcpCredentialProducer produces GoogleCredentials instead of the more generic Credentials? Not a big problem, just requires a non-null returning implementation of refreshAccessToken when talking with the mock server, while Credentials can be extended with returning all null values.

For this, I need to check the impact as we allow authentication for a lot of different ways, I too provides a mock for testing, if we can facilitate this it could be a good thing. 
There is also some services that are not yet authenticated via the global auth mechanism that is provided (like PubSub that mandates the GOOGLE_AUTHENTICATION env variable) if we change the auth, we need to check if we can improve this.
Please open a different issue for the authentication improvement.

**Comment by loicmathieu** [comment]
And also, is this endpoint-override mechanism only for Storage or is it possible for other services ? Some services handle emulators using env var is it the same thing or not ?

**Comment by PeterUlb** [comment]
PubSub also [exposes ](https://googleapis.dev/java/google-cloud-pubsub/latest/com/google/cloud/pubsub/v1/Subscriber.Builder.html#setEndpoint-java.lang.String-) it. 

> In all languages **except for Java** and C#, if you have set PUBSUB_EMULATOR_HOST as described in Setting environment variables, the Pub/Sub client libraries automatically call the API running in the local instance rather than Pub/Sub.

But for PubSub that's not enough. The emulator only works with plaintext. So a custom `ChannelProvider` is required. But since there's no way to expose such a Bean anyway, it's not really needed.

Other endpoints have something similar, but not often we could use it for the Producers.

I think storage makes most sense as of now. I'm not sure how much value there is in at least exposing the property to have a one-for-all stop for the configuration. That would allow to create pubsub subcribers with injection of `Authentication` and the optional override property.

So maybe expose a override property for all services which have it somewhere, and additionally implement it for cloud storage?

PS: For e.g. pubsub authentication I usually just Inject the Authentication, not relying on env variables at all. The Authentication producer itself already handles the env vars as backup.

**Comment by loicmathieu** [comment]
So I propose to only provides a config item for Storage for now, as you said, this is the one for which it makes sense.

> PS: For e.g. pubsub authentication I usually just Inject the Authentication, not relying on env variables at all. The Authentication producer itself already handles the env vars as backup.

I saw something like this some times ago, maybe it's just a matter of better documentation and changing the IT ;) PR are welcome :)
